steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/requestx-docker-repo/requestx-api:${SHORT_SHA}', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/requestx-docker-repo/requestx-api:${SHORT_SHA}']
  - name: gcr.io/cloud-builders/docker
    args: [ 'tag', 'us-west1-docker.pkg.dev/$PROJECT_ID/requestx-docker-repo/requestx-api:${SHORT_SHA}', 'us-west1-docker.pkg.dev/$PROJECT_ID/requestx-docker-repo/requestx-api:latest' ]
