version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-test_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-test_db}
      MYSQL_USER: ${MYSQL_USER:-test_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test_password}
    expose:
      - "8082"
    ports:
      - "8082:3306/tcp"

  migrations:
    image: rust:latest
    build:
      dockerfile: Dockerfile
    links:
      - mysql
    depends_on:
      - mysql
