//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gd_account_link")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, unique)]
	pub discord_id: u64,
	#[sea_orm(primary_key, auto_increment = false, unique)]
	pub gd_player_id: u64,
	#[sea_orm(primary_key, auto_increment = false, unique)]
	pub is_gd_account_linked: i8,
	#[sea_orm(unique)]
	pub gd_account_challenge: String,
	#[sea_orm(unique)]
	pub gd_account_hash: String,
	#[sea_orm(column_type = "VarBinary(StringLen::N(32))", unique)]
	pub gd_account_public_key: Vec<u8>,
	pub expiry: DateTimeUtc
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::DiscordId",
		to = "super::user::Column::DiscordId",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User3,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::GdPlayerId",
		to = "super::user::Column::GdPlayerId",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User2,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::IsGdAccountLinked",
		to = "super::user::Column::IsGdAccountLinked",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User1
}

impl ActiveModelBehavior for ActiveModel {}
