//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{Rating, Score};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "moderator")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub level_id: u64,
	pub score: Score,
	pub rating: Rating
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::level_request::Entity",
		from = "Column::LevelId",
		to = "super::level_request::Column::LevelId",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	LevelRequest
}

impl Related<super::level_request::Entity> for Entity {
	fn to() -> RelationDef { Relation::LevelRequest.def() }
}

impl ActiveModelBehavior for ActiveModel {}
