//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::{
	level_request::Entity as LevelRequest, moderator::Entity as Moderator,
	review::Entity as Review, reviewer::Entity as Reviewer, user::Entity as User
};
