//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "review")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub level_id: u64,
	pub discord_id: u64,
	pub review_content: String
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::DiscordId",
		to = "super::user::Column::DiscordId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef { Relation::User.def() }
}

impl ActiveModelBehavior for ActiveModel {}
