//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "request_rating")]
pub enum RequestRating {
	#[sea_orm(string_value = "one")]
	One,
	#[sea_orm(string_value = "two")]
	Two,
	#[sea_orm(string_value = "three")]
	Three,
	#[sea_orm(string_value = "four")]
	Four,
	#[sea_orm(string_value = "five")]
	Five,
	#[sea_orm(string_value = "six")]
	Six,
	#[sea_orm(string_value = "seven")]
	Seven,
	#[sea_orm(string_value = "eight")]
	Eight,
	#[sea_orm(string_value = "nine")]
	Nine,
	#[sea_orm(string_value = "ten")]
	Ten
}
