//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub discord_id: u64
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::level_request::Entity")]
	LevelRequest,
	#[sea_orm(has_many = "super::review::Entity")]
	Review
}

impl Related<super::level_request::Entity> for Entity {
	fn to() -> RelationDef { Relation::LevelRequest.def() }
}

impl Related<super::review::Entity> for Entity {
	fn to() -> RelationDef { Relation::Review.def() }
}

impl ActiveModelBehavior for ActiveModel {}
