//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub discord_id: u64,
	pub timestamp: Option<DateTimeUtc>,
	pub gd_player_id: Option<u64>,
	pub gd_account_hash: Option<String>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::level_request::Entity")]
	LevelRequest
}

impl Related<super::level_request::Entity> for Entity {
	fn to() -> RelationDef { Relation::LevelRequest.def() }
}

impl ActiveModelBehavior for ActiveModel {}
